language: ruby
cache: bundler
rvm:
- 2.3.1
addons:
  postgresql: '9.4'
# before_script:
# - psql -c "create role pm_app_test with createdb superuser login password 'test';"
#   -U postgres
script:
- bin/rake db:create
- bin/rake db:migrate
- bin/rspec
sudo: false