- name: Install PostgreSQL dependencies
  action: apt pkg={{item}} state=latest
  with_items:
    - python-pycurl
    - python-psycopg2

- name: Add PostgreSQL repo key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc

- name: Add PostgreSQL repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'

- name: Install PostgreSQL
  apt: pkg=postgresql-9.3 state=latest update_cache=true

- name: Restart PostgreSQL
  command: service postgresql restart
